/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.camunda.rest.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.Nullable;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * AuthorizationExceptionDtoAllOf
 */
@JsonPropertyOrder({
  AuthorizationExceptionDtoAllOf.JSON_PROPERTY_USER_ID,
  AuthorizationExceptionDtoAllOf.JSON_PROPERTY_MISSING_AUTHORIZATIONS
})
@JsonTypeName("AuthorizationExceptionDto_allOf")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen")
@Introspected
public class AuthorizationExceptionDtoAllOf {
    public static final String JSON_PROPERTY_USER_ID = "userId";
    private String userId;

    public static final String JSON_PROPERTY_MISSING_AUTHORIZATIONS = "missingAuthorizations";
    private List<MissingAuthorizationDto> missingAuthorizations = null;

    public AuthorizationExceptionDtoAllOf() {
    }

    public AuthorizationExceptionDtoAllOf userId(String userId) {
        this.userId = userId;
        return this;
    }

    /**
     * The id of the user that does not have expected permissions
     * @return userId
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_USER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getUserId() {
        return userId;
    }

    @JsonProperty(JSON_PROPERTY_USER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUserId(String userId) {
        this.userId = userId;
    }

    public AuthorizationExceptionDtoAllOf missingAuthorizations(List<MissingAuthorizationDto> missingAuthorizations) {
        this.missingAuthorizations = missingAuthorizations;
        return this;
    }

    public AuthorizationExceptionDtoAllOf addMissingAuthorizationsItem(MissingAuthorizationDto missingAuthorizationsItem) {
        if (this.missingAuthorizations == null) {
            this.missingAuthorizations = new ArrayList<>();
        }
        this.missingAuthorizations.add(missingAuthorizationsItem);
        return this;
    }

    /**
     * 
     * @return missingAuthorizations
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_MISSING_AUTHORIZATIONS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<MissingAuthorizationDto> getMissingAuthorizations() {
        return missingAuthorizations;
    }

    @JsonProperty(JSON_PROPERTY_MISSING_AUTHORIZATIONS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMissingAuthorizations(List<MissingAuthorizationDto> missingAuthorizations) {
        this.missingAuthorizations = missingAuthorizations;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuthorizationExceptionDtoAllOf authorizationExceptionDtoAllOf = (AuthorizationExceptionDtoAllOf) o;
        return Objects.equals(this.userId, authorizationExceptionDtoAllOf.userId) &&
            Objects.equals(this.missingAuthorizations, authorizationExceptionDtoAllOf.missingAuthorizations);
    }

    @Override
    public int hashCode() {
        return Objects.hash(userId, missingAuthorizations);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AuthorizationExceptionDtoAllOf {\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("    missingAuthorizations: ").append(toIndentedString(missingAuthorizations)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

