/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.camunda.rest.model;

import com.fasterxml.jackson.annotation.*;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.Nullable;

import javax.annotation.Generated;
import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * HistoricBatchDto
 */
@JsonPropertyOrder({
  HistoricBatchDto.JSON_PROPERTY_ID,
  HistoricBatchDto.JSON_PROPERTY_TYPE,
  HistoricBatchDto.JSON_PROPERTY_TOTAL_JOBS,
  HistoricBatchDto.JSON_PROPERTY_BATCH_JOBS_PER_SEED,
  HistoricBatchDto.JSON_PROPERTY_INVOCATIONS_PER_BATCH_JOB,
  HistoricBatchDto.JSON_PROPERTY_SEED_JOB_DEFINITION_ID,
  HistoricBatchDto.JSON_PROPERTY_MONITOR_JOB_DEFINITION_ID,
  HistoricBatchDto.JSON_PROPERTY_BATCH_JOB_DEFINITION_ID,
  HistoricBatchDto.JSON_PROPERTY_TENANT_ID,
  HistoricBatchDto.JSON_PROPERTY_CREATE_USER_ID,
  HistoricBatchDto.JSON_PROPERTY_START_TIME,
  HistoricBatchDto.JSON_PROPERTY_EXECUTION_START_TIME,
  HistoricBatchDto.JSON_PROPERTY_END_TIME,
  HistoricBatchDto.JSON_PROPERTY_REMOVAL_TIME
})
@JsonTypeName("HistoricBatchDto")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen")
@Introspected
public class HistoricBatchDto {
    public static final String JSON_PROPERTY_ID = "id";
    private String id;

    public static final String JSON_PROPERTY_TYPE = "type";
    private String type;

    public static final String JSON_PROPERTY_TOTAL_JOBS = "totalJobs";
    private Integer totalJobs;

    public static final String JSON_PROPERTY_BATCH_JOBS_PER_SEED = "batchJobsPerSeed";
    private Integer batchJobsPerSeed;

    public static final String JSON_PROPERTY_INVOCATIONS_PER_BATCH_JOB = "invocationsPerBatchJob";
    private Integer invocationsPerBatchJob;

    public static final String JSON_PROPERTY_SEED_JOB_DEFINITION_ID = "seedJobDefinitionId";
    private String seedJobDefinitionId;

    public static final String JSON_PROPERTY_MONITOR_JOB_DEFINITION_ID = "monitorJobDefinitionId";
    private String monitorJobDefinitionId;

    public static final String JSON_PROPERTY_BATCH_JOB_DEFINITION_ID = "batchJobDefinitionId";
    private String batchJobDefinitionId;

    public static final String JSON_PROPERTY_TENANT_ID = "tenantId";
    private String tenantId;

    public static final String JSON_PROPERTY_CREATE_USER_ID = "createUserId";
    private String createUserId;

    public static final String JSON_PROPERTY_START_TIME = "startTime";
    private OffsetDateTime startTime;

    public static final String JSON_PROPERTY_EXECUTION_START_TIME = "executionStartTime";
    private OffsetDateTime executionStartTime;

    public static final String JSON_PROPERTY_END_TIME = "endTime";
    private OffsetDateTime endTime;

    public static final String JSON_PROPERTY_REMOVAL_TIME = "removalTime";
    private OffsetDateTime removalTime;

    public HistoricBatchDto() {
    }

    public HistoricBatchDto id(String id) {
        this.id = id;
        return this;
    }

    /**
     * The id of the batch.
     * @return id
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(String id) {
        this.id = id;
    }

    public HistoricBatchDto type(String type) {
        this.type = type;
        return this;
    }

    /**
     * The type of the batch. See the [User Guide](https://docs.camunda.org/manual/7.18/user-guide/process-engine/batch/#creating-a-batch) for more information about batch types.
     * @return type
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getType() {
        return type;
    }

    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setType(String type) {
        this.type = type;
    }

    public HistoricBatchDto totalJobs(Integer totalJobs) {
        this.totalJobs = totalJobs;
        return this;
    }

    /**
     *  The total jobs of a batch is the number of batch execution jobs required to complete the batch. 
     * @return totalJobs
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_TOTAL_JOBS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getTotalJobs() {
        return totalJobs;
    }

    @JsonProperty(JSON_PROPERTY_TOTAL_JOBS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTotalJobs(Integer totalJobs) {
        this.totalJobs = totalJobs;
    }

    public HistoricBatchDto batchJobsPerSeed(Integer batchJobsPerSeed) {
        this.batchJobsPerSeed = batchJobsPerSeed;
        return this;
    }

    /**
     *  The number of batch execution jobs created per seed job invocation. The batch seed job is invoked until it has created all batch execution jobs required by the batch (see &#x60;totalJobs&#x60; property). 
     * @return batchJobsPerSeed
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_BATCH_JOBS_PER_SEED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getBatchJobsPerSeed() {
        return batchJobsPerSeed;
    }

    @JsonProperty(JSON_PROPERTY_BATCH_JOBS_PER_SEED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setBatchJobsPerSeed(Integer batchJobsPerSeed) {
        this.batchJobsPerSeed = batchJobsPerSeed;
    }

    public HistoricBatchDto invocationsPerBatchJob(Integer invocationsPerBatchJob) {
        this.invocationsPerBatchJob = invocationsPerBatchJob;
        return this;
    }

    /**
     *  Every batch execution job invokes the command executed by the batch &#x60;invocationsPerBatchJob&#x60; times. E.g., for a process instance migration batch this specifies the number of process instances which are migrated per batch execution job. 
     * @return invocationsPerBatchJob
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_INVOCATIONS_PER_BATCH_JOB)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getInvocationsPerBatchJob() {
        return invocationsPerBatchJob;
    }

    @JsonProperty(JSON_PROPERTY_INVOCATIONS_PER_BATCH_JOB)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setInvocationsPerBatchJob(Integer invocationsPerBatchJob) {
        this.invocationsPerBatchJob = invocationsPerBatchJob;
    }

    public HistoricBatchDto seedJobDefinitionId(String seedJobDefinitionId) {
        this.seedJobDefinitionId = seedJobDefinitionId;
        return this;
    }

    /**
     * The job definition id for the seed jobs of this batch.
     * @return seedJobDefinitionId
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_SEED_JOB_DEFINITION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getSeedJobDefinitionId() {
        return seedJobDefinitionId;
    }

    @JsonProperty(JSON_PROPERTY_SEED_JOB_DEFINITION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSeedJobDefinitionId(String seedJobDefinitionId) {
        this.seedJobDefinitionId = seedJobDefinitionId;
    }

    public HistoricBatchDto monitorJobDefinitionId(String monitorJobDefinitionId) {
        this.monitorJobDefinitionId = monitorJobDefinitionId;
        return this;
    }

    /**
     * The job definition id for the monitor jobs of this batch.
     * @return monitorJobDefinitionId
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_MONITOR_JOB_DEFINITION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getMonitorJobDefinitionId() {
        return monitorJobDefinitionId;
    }

    @JsonProperty(JSON_PROPERTY_MONITOR_JOB_DEFINITION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMonitorJobDefinitionId(String monitorJobDefinitionId) {
        this.monitorJobDefinitionId = monitorJobDefinitionId;
    }

    public HistoricBatchDto batchJobDefinitionId(String batchJobDefinitionId) {
        this.batchJobDefinitionId = batchJobDefinitionId;
        return this;
    }

    /**
     * The job definition id for the batch execution jobs of this batch.
     * @return batchJobDefinitionId
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_BATCH_JOB_DEFINITION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getBatchJobDefinitionId() {
        return batchJobDefinitionId;
    }

    @JsonProperty(JSON_PROPERTY_BATCH_JOB_DEFINITION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setBatchJobDefinitionId(String batchJobDefinitionId) {
        this.batchJobDefinitionId = batchJobDefinitionId;
    }

    public HistoricBatchDto tenantId(String tenantId) {
        this.tenantId = tenantId;
        return this;
    }

    /**
     * The tenant id of the batch.
     * @return tenantId
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_TENANT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getTenantId() {
        return tenantId;
    }

    @JsonProperty(JSON_PROPERTY_TENANT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    public HistoricBatchDto createUserId(String createUserId) {
        this.createUserId = createUserId;
        return this;
    }

    /**
     * The batch creator&#39;s user id.
     * @return createUserId
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_CREATE_USER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getCreateUserId() {
        return createUserId;
    }

    @JsonProperty(JSON_PROPERTY_CREATE_USER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    public HistoricBatchDto startTime(OffsetDateTime startTime) {
        this.startTime = startTime;
        return this;
    }

    /**
     * The time the batch was started. Default format &#x60;yyyy-MM-dd&#39;T&#39;HH:mm:ss.SSSZ&#x60;. For further information, please see the [documentation](https://docs.camunda.org/manual/7.18/reference/rest/overview/date-format/)
     * @return startTime
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_START_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public OffsetDateTime getStartTime() {
        return startTime;
    }

    @JsonProperty(JSON_PROPERTY_START_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public void setStartTime(OffsetDateTime startTime) {
        this.startTime = startTime;
    }

    public HistoricBatchDto executionStartTime(OffsetDateTime executionStartTime) {
        this.executionStartTime = executionStartTime;
        return this;
    }

    /**
     * The time the batch execution was started, i.e., at least one batch job has been executed. Default format &#x60;yyyy-MM-dd&#39;T&#39;HH:mm:ss.SSSZ&#x60;. For further information, please see the [documentation] (https://docs.camunda.org/manual/7.18/reference/rest/overview/date-format/)
     * @return executionStartTime
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_EXECUTION_START_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public OffsetDateTime getExecutionStartTime() {
        return executionStartTime;
    }

    @JsonProperty(JSON_PROPERTY_EXECUTION_START_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public void setExecutionStartTime(OffsetDateTime executionStartTime) {
        this.executionStartTime = executionStartTime;
    }

    public HistoricBatchDto endTime(OffsetDateTime endTime) {
        this.endTime = endTime;
        return this;
    }

    /**
     * The time the batch ended. Default format &#x60;yyyy-MM-dd&#39;T&#39;HH:mm:ss.SSSZ&#x60;. For further information, please see the [documentation](https://docs.camunda.org/manual/7.18/reference/rest/overview/date-format/)
     * @return endTime
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_END_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public OffsetDateTime getEndTime() {
        return endTime;
    }

    @JsonProperty(JSON_PROPERTY_END_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public void setEndTime(OffsetDateTime endTime) {
        this.endTime = endTime;
    }

    public HistoricBatchDto removalTime(OffsetDateTime removalTime) {
        this.removalTime = removalTime;
        return this;
    }

    /**
     * The time after which the historic batch should be removed by the History Cleanup job. Default format &#x60;yyyy-MM-dd&#39;T&#39;HH:mm:ss.SSSZ&#x60;. For further information, please see the [documentation](https://docs.camunda.org/manual/7.18/reference/rest/overview/date-format/)
     * @return removalTime
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_REMOVAL_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public OffsetDateTime getRemovalTime() {
        return removalTime;
    }

    @JsonProperty(JSON_PROPERTY_REMOVAL_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public void setRemovalTime(OffsetDateTime removalTime) {
        this.removalTime = removalTime;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        HistoricBatchDto historicBatchDto = (HistoricBatchDto) o;
        return Objects.equals(this.id, historicBatchDto.id) &&
            Objects.equals(this.type, historicBatchDto.type) &&
            Objects.equals(this.totalJobs, historicBatchDto.totalJobs) &&
            Objects.equals(this.batchJobsPerSeed, historicBatchDto.batchJobsPerSeed) &&
            Objects.equals(this.invocationsPerBatchJob, historicBatchDto.invocationsPerBatchJob) &&
            Objects.equals(this.seedJobDefinitionId, historicBatchDto.seedJobDefinitionId) &&
            Objects.equals(this.monitorJobDefinitionId, historicBatchDto.monitorJobDefinitionId) &&
            Objects.equals(this.batchJobDefinitionId, historicBatchDto.batchJobDefinitionId) &&
            Objects.equals(this.tenantId, historicBatchDto.tenantId) &&
            Objects.equals(this.createUserId, historicBatchDto.createUserId) &&
            Objects.equals(this.startTime, historicBatchDto.startTime) &&
            Objects.equals(this.executionStartTime, historicBatchDto.executionStartTime) &&
            Objects.equals(this.endTime, historicBatchDto.endTime) &&
            Objects.equals(this.removalTime, historicBatchDto.removalTime);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, type, totalJobs, batchJobsPerSeed, invocationsPerBatchJob, seedJobDefinitionId, monitorJobDefinitionId, batchJobDefinitionId, tenantId, createUserId, startTime, executionStartTime, endTime, removalTime);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class HistoricBatchDto {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    totalJobs: ").append(toIndentedString(totalJobs)).append("\n");
        sb.append("    batchJobsPerSeed: ").append(toIndentedString(batchJobsPerSeed)).append("\n");
        sb.append("    invocationsPerBatchJob: ").append(toIndentedString(invocationsPerBatchJob)).append("\n");
        sb.append("    seedJobDefinitionId: ").append(toIndentedString(seedJobDefinitionId)).append("\n");
        sb.append("    monitorJobDefinitionId: ").append(toIndentedString(monitorJobDefinitionId)).append("\n");
        sb.append("    batchJobDefinitionId: ").append(toIndentedString(batchJobDefinitionId)).append("\n");
        sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
        sb.append("    createUserId: ").append(toIndentedString(createUserId)).append("\n");
        sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
        sb.append("    executionStartTime: ").append(toIndentedString(executionStartTime)).append("\n");
        sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
        sb.append("    removalTime: ").append(toIndentedString(removalTime)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

