/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.camunda.rest.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.Nullable;

import javax.annotation.Generated;
import java.util.*;

/**
 * ProcessInstanceWithVariablesDto
 */
@JsonPropertyOrder({
  ProcessInstanceWithVariablesDto.JSON_PROPERTY_VARIABLES,
  ProcessInstanceWithVariablesDto.JSON_PROPERTY_ID,
  ProcessInstanceWithVariablesDto.JSON_PROPERTY_DEFINITION_ID,
  ProcessInstanceWithVariablesDto.JSON_PROPERTY_BUSINESS_KEY,
  ProcessInstanceWithVariablesDto.JSON_PROPERTY_CASE_INSTANCE_ID,
  ProcessInstanceWithVariablesDto.JSON_PROPERTY_ENDED,
  ProcessInstanceWithVariablesDto.JSON_PROPERTY_SUSPENDED,
  ProcessInstanceWithVariablesDto.JSON_PROPERTY_TENANT_ID,
  ProcessInstanceWithVariablesDto.JSON_PROPERTY_LINKS
})
@JsonTypeName("ProcessInstanceWithVariablesDto")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen")
@Introspected
public class ProcessInstanceWithVariablesDto {
    public static final String JSON_PROPERTY_VARIABLES = "variables";
    private Map<String, VariableValueDto> variables = null;

    public static final String JSON_PROPERTY_ID = "id";
    private String id;

    public static final String JSON_PROPERTY_DEFINITION_ID = "definitionId";
    private String definitionId;

    public static final String JSON_PROPERTY_BUSINESS_KEY = "businessKey";
    private String businessKey;

    public static final String JSON_PROPERTY_CASE_INSTANCE_ID = "caseInstanceId";
    private String caseInstanceId;

    public static final String JSON_PROPERTY_ENDED = "ended";
    private Boolean ended;

    public static final String JSON_PROPERTY_SUSPENDED = "suspended";
    private Boolean suspended;

    public static final String JSON_PROPERTY_TENANT_ID = "tenantId";
    private String tenantId;

    public static final String JSON_PROPERTY_LINKS = "links";
    private List<AtomLink> links = null;

    public ProcessInstanceWithVariablesDto() {
    }

    public ProcessInstanceWithVariablesDto variables(Map<String, VariableValueDto> variables) {
        this.variables = variables;
        return this;
    }

    public ProcessInstanceWithVariablesDto putVariablesItem(String key, VariableValueDto variablesItem) {
        if (this.variables == null) {
            this.variables = new HashMap<>();
        }
        this.variables.put(key, variablesItem);
        return this;
  }

    /**
     * The id of the process instance.
     * @return variables
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_VARIABLES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Map<String, VariableValueDto> getVariables() {
        return variables;
    }

    @JsonProperty(JSON_PROPERTY_VARIABLES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVariables(Map<String, VariableValueDto> variables) {
        this.variables = variables;
    }

    public ProcessInstanceWithVariablesDto id(String id) {
        this.id = id;
        return this;
    }

    /**
     * The id of the process instance.
     * @return id
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(String id) {
        this.id = id;
    }

    public ProcessInstanceWithVariablesDto definitionId(String definitionId) {
        this.definitionId = definitionId;
        return this;
    }

    /**
     * The id of the process definition that this process instance belongs to.
     * @return definitionId
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_DEFINITION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getDefinitionId() {
        return definitionId;
    }

    @JsonProperty(JSON_PROPERTY_DEFINITION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDefinitionId(String definitionId) {
        this.definitionId = definitionId;
    }

    public ProcessInstanceWithVariablesDto businessKey(String businessKey) {
        this.businessKey = businessKey;
        return this;
    }

    /**
     * The business key of the process instance.
     * @return businessKey
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_BUSINESS_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getBusinessKey() {
        return businessKey;
    }

    @JsonProperty(JSON_PROPERTY_BUSINESS_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setBusinessKey(String businessKey) {
        this.businessKey = businessKey;
    }

    public ProcessInstanceWithVariablesDto caseInstanceId(String caseInstanceId) {
        this.caseInstanceId = caseInstanceId;
        return this;
    }

    /**
     * The id of the case instance associated with the process instance.
     * @return caseInstanceId
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_CASE_INSTANCE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getCaseInstanceId() {
        return caseInstanceId;
    }

    @JsonProperty(JSON_PROPERTY_CASE_INSTANCE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCaseInstanceId(String caseInstanceId) {
        this.caseInstanceId = caseInstanceId;
    }

    public ProcessInstanceWithVariablesDto ended(Boolean ended) {
        this.ended = ended;
        return this;
    }

    /**
     * A flag indicating whether the process instance has ended or not. Deprecated: will always be false!
     * @return ended
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_ENDED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getEnded() {
        return ended;
    }

    @JsonProperty(JSON_PROPERTY_ENDED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEnded(Boolean ended) {
        this.ended = ended;
    }

    public ProcessInstanceWithVariablesDto suspended(Boolean suspended) {
        this.suspended = suspended;
        return this;
    }

    /**
     * A flag indicating whether the process instance is suspended or not.
     * @return suspended
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_SUSPENDED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getSuspended() {
        return suspended;
    }

    @JsonProperty(JSON_PROPERTY_SUSPENDED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSuspended(Boolean suspended) {
        this.suspended = suspended;
    }

    public ProcessInstanceWithVariablesDto tenantId(String tenantId) {
        this.tenantId = tenantId;
        return this;
    }

    /**
     * The tenant id of the process instance.
     * @return tenantId
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_TENANT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getTenantId() {
        return tenantId;
    }

    @JsonProperty(JSON_PROPERTY_TENANT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    public ProcessInstanceWithVariablesDto links(List<AtomLink> links) {
        this.links = links;
        return this;
    }

    public ProcessInstanceWithVariablesDto addLinksItem(AtomLink linksItem) {
        if (this.links == null) {
            this.links = new ArrayList<>();
        }
        this.links.add(linksItem);
        return this;
    }

    /**
     * The links associated to this resource, with &#x60;method&#x60;, &#x60;href&#x60; and &#x60;rel&#x60;.
     * @return links
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_LINKS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<AtomLink> getLinks() {
        return links;
    }

    @JsonProperty(JSON_PROPERTY_LINKS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLinks(List<AtomLink> links) {
        this.links = links;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProcessInstanceWithVariablesDto processInstanceWithVariablesDto = (ProcessInstanceWithVariablesDto) o;
        return Objects.equals(this.variables, processInstanceWithVariablesDto.variables) &&
            Objects.equals(this.id, processInstanceWithVariablesDto.id) &&
            Objects.equals(this.definitionId, processInstanceWithVariablesDto.definitionId) &&
            Objects.equals(this.businessKey, processInstanceWithVariablesDto.businessKey) &&
            Objects.equals(this.caseInstanceId, processInstanceWithVariablesDto.caseInstanceId) &&
            Objects.equals(this.ended, processInstanceWithVariablesDto.ended) &&
            Objects.equals(this.suspended, processInstanceWithVariablesDto.suspended) &&
            Objects.equals(this.tenantId, processInstanceWithVariablesDto.tenantId) &&
            Objects.equals(this.links, processInstanceWithVariablesDto.links);
    }

    @Override
    public int hashCode() {
        return Objects.hash(variables, id, definitionId, businessKey, caseInstanceId, ended, suspended, tenantId, links);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ProcessInstanceWithVariablesDto {\n");
        sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    definitionId: ").append(toIndentedString(definitionId)).append("\n");
        sb.append("    businessKey: ").append(toIndentedString(businessKey)).append("\n");
        sb.append("    caseInstanceId: ").append(toIndentedString(caseInstanceId)).append("\n");
        sb.append("    ended: ").append(toIndentedString(ended)).append("\n");
        sb.append("    suspended: ").append(toIndentedString(suspended)).append("\n");
        sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
        sb.append("    links: ").append(toIndentedString(links)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

