/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.camunda.rest.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.Nullable;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * A process instance query which defines a group of process instances
 */
@JsonPropertyOrder({
  ProcessInstanceQueryDto.JSON_PROPERTY_DEPLOYMENT_ID,
  ProcessInstanceQueryDto.JSON_PROPERTY_PROCESS_DEFINITION_ID,
  ProcessInstanceQueryDto.JSON_PROPERTY_PROCESS_DEFINITION_KEY,
  ProcessInstanceQueryDto.JSON_PROPERTY_PROCESS_DEFINITION_KEY_IN,
  ProcessInstanceQueryDto.JSON_PROPERTY_PROCESS_DEFINITION_KEY_NOT_IN,
  ProcessInstanceQueryDto.JSON_PROPERTY_BUSINESS_KEY,
  ProcessInstanceQueryDto.JSON_PROPERTY_BUSINESS_KEY_LIKE,
  ProcessInstanceQueryDto.JSON_PROPERTY_CASE_INSTANCE_ID,
  ProcessInstanceQueryDto.JSON_PROPERTY_SUPER_PROCESS_INSTANCE,
  ProcessInstanceQueryDto.JSON_PROPERTY_SUB_PROCESS_INSTANCE,
  ProcessInstanceQueryDto.JSON_PROPERTY_SUPER_CASE_INSTANCE,
  ProcessInstanceQueryDto.JSON_PROPERTY_SUB_CASE_INSTANCE,
  ProcessInstanceQueryDto.JSON_PROPERTY_ACTIVE,
  ProcessInstanceQueryDto.JSON_PROPERTY_SUSPENDED,
  ProcessInstanceQueryDto.JSON_PROPERTY_PROCESS_INSTANCE_IDS,
  ProcessInstanceQueryDto.JSON_PROPERTY_WITH_INCIDENT,
  ProcessInstanceQueryDto.JSON_PROPERTY_INCIDENT_ID,
  ProcessInstanceQueryDto.JSON_PROPERTY_INCIDENT_TYPE,
  ProcessInstanceQueryDto.JSON_PROPERTY_INCIDENT_MESSAGE,
  ProcessInstanceQueryDto.JSON_PROPERTY_INCIDENT_MESSAGE_LIKE,
  ProcessInstanceQueryDto.JSON_PROPERTY_TENANT_ID_IN,
  ProcessInstanceQueryDto.JSON_PROPERTY_WITHOUT_TENANT_ID,
  ProcessInstanceQueryDto.JSON_PROPERTY_PROCESS_DEFINITION_WITHOUT_TENANT_ID,
  ProcessInstanceQueryDto.JSON_PROPERTY_ACTIVITY_ID_IN,
  ProcessInstanceQueryDto.JSON_PROPERTY_ROOT_PROCESS_INSTANCES,
  ProcessInstanceQueryDto.JSON_PROPERTY_LEAF_PROCESS_INSTANCES,
  ProcessInstanceQueryDto.JSON_PROPERTY_VARIABLES,
  ProcessInstanceQueryDto.JSON_PROPERTY_VARIABLE_NAMES_IGNORE_CASE,
  ProcessInstanceQueryDto.JSON_PROPERTY_VARIABLE_VALUES_IGNORE_CASE,
  ProcessInstanceQueryDto.JSON_PROPERTY_OR_QUERIES,
  ProcessInstanceQueryDto.JSON_PROPERTY_SORTING
})
@JsonTypeName("ProcessInstanceQueryDto")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen")
@Introspected
public class ProcessInstanceQueryDto {
    public static final String JSON_PROPERTY_DEPLOYMENT_ID = "deploymentId";
    private String deploymentId;

    public static final String JSON_PROPERTY_PROCESS_DEFINITION_ID = "processDefinitionId";
    private String processDefinitionId;

    public static final String JSON_PROPERTY_PROCESS_DEFINITION_KEY = "processDefinitionKey";
    private String processDefinitionKey;

    public static final String JSON_PROPERTY_PROCESS_DEFINITION_KEY_IN = "processDefinitionKeyIn";
    private List<String> processDefinitionKeyIn = null;

    public static final String JSON_PROPERTY_PROCESS_DEFINITION_KEY_NOT_IN = "processDefinitionKeyNotIn";
    private List<String> processDefinitionKeyNotIn = null;

    public static final String JSON_PROPERTY_BUSINESS_KEY = "businessKey";
    private String businessKey;

    public static final String JSON_PROPERTY_BUSINESS_KEY_LIKE = "businessKeyLike";
    private String businessKeyLike;

    public static final String JSON_PROPERTY_CASE_INSTANCE_ID = "caseInstanceId";
    private String caseInstanceId;

    public static final String JSON_PROPERTY_SUPER_PROCESS_INSTANCE = "superProcessInstance";
    private String superProcessInstance;

    public static final String JSON_PROPERTY_SUB_PROCESS_INSTANCE = "subProcessInstance";
    private String subProcessInstance;

    public static final String JSON_PROPERTY_SUPER_CASE_INSTANCE = "superCaseInstance";
    private String superCaseInstance;

    public static final String JSON_PROPERTY_SUB_CASE_INSTANCE = "subCaseInstance";
    private String subCaseInstance;

    public static final String JSON_PROPERTY_ACTIVE = "active";
    private Boolean active;

    public static final String JSON_PROPERTY_SUSPENDED = "suspended";
    private Boolean suspended;

    public static final String JSON_PROPERTY_PROCESS_INSTANCE_IDS = "processInstanceIds";
    private List<String> processInstanceIds = null;

    public static final String JSON_PROPERTY_WITH_INCIDENT = "withIncident";
    private Boolean withIncident;

    public static final String JSON_PROPERTY_INCIDENT_ID = "incidentId";
    private String incidentId;

    public static final String JSON_PROPERTY_INCIDENT_TYPE = "incidentType";
    private String incidentType;

    public static final String JSON_PROPERTY_INCIDENT_MESSAGE = "incidentMessage";
    private String incidentMessage;

    public static final String JSON_PROPERTY_INCIDENT_MESSAGE_LIKE = "incidentMessageLike";
    private String incidentMessageLike;

    public static final String JSON_PROPERTY_TENANT_ID_IN = "tenantIdIn";
    private List<String> tenantIdIn = null;

    public static final String JSON_PROPERTY_WITHOUT_TENANT_ID = "withoutTenantId";
    private Boolean withoutTenantId;

    public static final String JSON_PROPERTY_PROCESS_DEFINITION_WITHOUT_TENANT_ID = "processDefinitionWithoutTenantId";
    private Boolean processDefinitionWithoutTenantId;

    public static final String JSON_PROPERTY_ACTIVITY_ID_IN = "activityIdIn";
    private List<String> activityIdIn = null;

    public static final String JSON_PROPERTY_ROOT_PROCESS_INSTANCES = "rootProcessInstances";
    private Boolean rootProcessInstances;

    public static final String JSON_PROPERTY_LEAF_PROCESS_INSTANCES = "leafProcessInstances";
    private Boolean leafProcessInstances;

    public static final String JSON_PROPERTY_VARIABLES = "variables";
    private List<VariableQueryParameterDto> variables = null;

    public static final String JSON_PROPERTY_VARIABLE_NAMES_IGNORE_CASE = "variableNamesIgnoreCase";
    private Boolean variableNamesIgnoreCase;

    public static final String JSON_PROPERTY_VARIABLE_VALUES_IGNORE_CASE = "variableValuesIgnoreCase";
    private Boolean variableValuesIgnoreCase;

    public static final String JSON_PROPERTY_OR_QUERIES = "orQueries";
    private List<ProcessInstanceQueryDto> orQueries = null;

    public static final String JSON_PROPERTY_SORTING = "sorting";
    private List<ProcessInstanceQueryDtoSortingInner> sorting = null;

    public ProcessInstanceQueryDto() {
    }

    public ProcessInstanceQueryDto deploymentId(String deploymentId) {
        this.deploymentId = deploymentId;
        return this;
    }

    /**
     * Filter by the deployment the id belongs to.
     * @return deploymentId
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_DEPLOYMENT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getDeploymentId() {
        return deploymentId;
    }

    @JsonProperty(JSON_PROPERTY_DEPLOYMENT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeploymentId(String deploymentId) {
        this.deploymentId = deploymentId;
    }

    public ProcessInstanceQueryDto processDefinitionId(String processDefinitionId) {
        this.processDefinitionId = processDefinitionId;
        return this;
    }

    /**
     * Filter by the process definition the instances run on.
     * @return processDefinitionId
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_PROCESS_DEFINITION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getProcessDefinitionId() {
        return processDefinitionId;
    }

    @JsonProperty(JSON_PROPERTY_PROCESS_DEFINITION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProcessDefinitionId(String processDefinitionId) {
        this.processDefinitionId = processDefinitionId;
    }

    public ProcessInstanceQueryDto processDefinitionKey(String processDefinitionKey) {
        this.processDefinitionKey = processDefinitionKey;
        return this;
    }

    /**
     * Filter by the key of the process definition the instances run on.
     * @return processDefinitionKey
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_PROCESS_DEFINITION_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getProcessDefinitionKey() {
        return processDefinitionKey;
    }

    @JsonProperty(JSON_PROPERTY_PROCESS_DEFINITION_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProcessDefinitionKey(String processDefinitionKey) {
        this.processDefinitionKey = processDefinitionKey;
    }

    public ProcessInstanceQueryDto processDefinitionKeyIn(List<String> processDefinitionKeyIn) {
        this.processDefinitionKeyIn = processDefinitionKeyIn;
        return this;
    }

    public ProcessInstanceQueryDto addProcessDefinitionKeyInItem(String processDefinitionKeyInItem) {
        if (this.processDefinitionKeyIn == null) {
            this.processDefinitionKeyIn = new ArrayList<>();
        }
        this.processDefinitionKeyIn.add(processDefinitionKeyInItem);
        return this;
    }

    /**
     * Filter by a list of process definition keys. A process instance must have one of the given process definition keys. Must be a JSON array of Strings.
     * @return processDefinitionKeyIn
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_PROCESS_DEFINITION_KEY_IN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<String> getProcessDefinitionKeyIn() {
        return processDefinitionKeyIn;
    }

    @JsonProperty(JSON_PROPERTY_PROCESS_DEFINITION_KEY_IN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProcessDefinitionKeyIn(List<String> processDefinitionKeyIn) {
        this.processDefinitionKeyIn = processDefinitionKeyIn;
    }

    public ProcessInstanceQueryDto processDefinitionKeyNotIn(List<String> processDefinitionKeyNotIn) {
        this.processDefinitionKeyNotIn = processDefinitionKeyNotIn;
        return this;
    }

    public ProcessInstanceQueryDto addProcessDefinitionKeyNotInItem(String processDefinitionKeyNotInItem) {
        if (this.processDefinitionKeyNotIn == null) {
            this.processDefinitionKeyNotIn = new ArrayList<>();
        }
        this.processDefinitionKeyNotIn.add(processDefinitionKeyNotInItem);
        return this;
    }

    /**
     * Exclude instances by a list of process definition keys. A process instance must not have one of the given process definition keys. Must be a JSON array of Strings.
     * @return processDefinitionKeyNotIn
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_PROCESS_DEFINITION_KEY_NOT_IN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<String> getProcessDefinitionKeyNotIn() {
        return processDefinitionKeyNotIn;
    }

    @JsonProperty(JSON_PROPERTY_PROCESS_DEFINITION_KEY_NOT_IN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProcessDefinitionKeyNotIn(List<String> processDefinitionKeyNotIn) {
        this.processDefinitionKeyNotIn = processDefinitionKeyNotIn;
    }

    public ProcessInstanceQueryDto businessKey(String businessKey) {
        this.businessKey = businessKey;
        return this;
    }

    /**
     * Filter by process instance business key.
     * @return businessKey
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_BUSINESS_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getBusinessKey() {
        return businessKey;
    }

    @JsonProperty(JSON_PROPERTY_BUSINESS_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setBusinessKey(String businessKey) {
        this.businessKey = businessKey;
    }

    public ProcessInstanceQueryDto businessKeyLike(String businessKeyLike) {
        this.businessKeyLike = businessKeyLike;
        return this;
    }

    /**
     * Filter by process instance business key that the parameter is a substring of.
     * @return businessKeyLike
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_BUSINESS_KEY_LIKE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getBusinessKeyLike() {
        return businessKeyLike;
    }

    @JsonProperty(JSON_PROPERTY_BUSINESS_KEY_LIKE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setBusinessKeyLike(String businessKeyLike) {
        this.businessKeyLike = businessKeyLike;
    }

    public ProcessInstanceQueryDto caseInstanceId(String caseInstanceId) {
        this.caseInstanceId = caseInstanceId;
        return this;
    }

    /**
     * Filter by case instance id.
     * @return caseInstanceId
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_CASE_INSTANCE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getCaseInstanceId() {
        return caseInstanceId;
    }

    @JsonProperty(JSON_PROPERTY_CASE_INSTANCE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCaseInstanceId(String caseInstanceId) {
        this.caseInstanceId = caseInstanceId;
    }

    public ProcessInstanceQueryDto superProcessInstance(String superProcessInstance) {
        this.superProcessInstance = superProcessInstance;
        return this;
    }

    /**
     * Restrict query to all process instances that are sub process instances of the given process instance. Takes a process instance id.
     * @return superProcessInstance
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_SUPER_PROCESS_INSTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getSuperProcessInstance() {
        return superProcessInstance;
    }

    @JsonProperty(JSON_PROPERTY_SUPER_PROCESS_INSTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSuperProcessInstance(String superProcessInstance) {
        this.superProcessInstance = superProcessInstance;
    }

    public ProcessInstanceQueryDto subProcessInstance(String subProcessInstance) {
        this.subProcessInstance = subProcessInstance;
        return this;
    }

    /**
     * Restrict query to all process instances that have the given process instance as a sub process instance. Takes a process instance id.
     * @return subProcessInstance
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_SUB_PROCESS_INSTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getSubProcessInstance() {
        return subProcessInstance;
    }

    @JsonProperty(JSON_PROPERTY_SUB_PROCESS_INSTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSubProcessInstance(String subProcessInstance) {
        this.subProcessInstance = subProcessInstance;
    }

    public ProcessInstanceQueryDto superCaseInstance(String superCaseInstance) {
        this.superCaseInstance = superCaseInstance;
        return this;
    }

    /**
     * Restrict query to all process instances that are sub process instances of the given case instance. Takes a case instance id.
     * @return superCaseInstance
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_SUPER_CASE_INSTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getSuperCaseInstance() {
        return superCaseInstance;
    }

    @JsonProperty(JSON_PROPERTY_SUPER_CASE_INSTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSuperCaseInstance(String superCaseInstance) {
        this.superCaseInstance = superCaseInstance;
    }

    public ProcessInstanceQueryDto subCaseInstance(String subCaseInstance) {
        this.subCaseInstance = subCaseInstance;
        return this;
    }

    /**
     * Restrict query to all process instances that have the given case instance as a sub case instance. Takes a case instance id.
     * @return subCaseInstance
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_SUB_CASE_INSTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getSubCaseInstance() {
        return subCaseInstance;
    }

    @JsonProperty(JSON_PROPERTY_SUB_CASE_INSTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSubCaseInstance(String subCaseInstance) {
        this.subCaseInstance = subCaseInstance;
    }

    public ProcessInstanceQueryDto active(Boolean active) {
        this.active = active;
        return this;
    }

    /**
     * Only include active process instances. Value may only be true, as false is the default behavior.
     * @return active
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_ACTIVE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getActive() {
        return active;
    }

    @JsonProperty(JSON_PROPERTY_ACTIVE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setActive(Boolean active) {
        this.active = active;
    }

    public ProcessInstanceQueryDto suspended(Boolean suspended) {
        this.suspended = suspended;
        return this;
    }

    /**
     * Only include suspended process instances. Value may only be true, as false is the default behavior.
     * @return suspended
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_SUSPENDED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getSuspended() {
        return suspended;
    }

    @JsonProperty(JSON_PROPERTY_SUSPENDED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSuspended(Boolean suspended) {
        this.suspended = suspended;
    }

    public ProcessInstanceQueryDto processInstanceIds(List<String> processInstanceIds) {
        this.processInstanceIds = processInstanceIds;
        return this;
    }

    public ProcessInstanceQueryDto addProcessInstanceIdsItem(String processInstanceIdsItem) {
        if (this.processInstanceIds == null) {
            this.processInstanceIds = new ArrayList<>();
        }
        this.processInstanceIds.add(processInstanceIdsItem);
        return this;
    }

    /**
     * Filter by a list of process instance ids. Must be a JSON array of Strings.
     * @return processInstanceIds
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_PROCESS_INSTANCE_IDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<String> getProcessInstanceIds() {
        return processInstanceIds;
    }

    @JsonProperty(JSON_PROPERTY_PROCESS_INSTANCE_IDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProcessInstanceIds(List<String> processInstanceIds) {
        this.processInstanceIds = processInstanceIds;
    }

    public ProcessInstanceQueryDto withIncident(Boolean withIncident) {
        this.withIncident = withIncident;
        return this;
    }

    /**
     * Filter by presence of incidents. Selects only process instances that have an incident.
     * @return withIncident
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_WITH_INCIDENT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getWithIncident() {
        return withIncident;
    }

    @JsonProperty(JSON_PROPERTY_WITH_INCIDENT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setWithIncident(Boolean withIncident) {
        this.withIncident = withIncident;
    }

    public ProcessInstanceQueryDto incidentId(String incidentId) {
        this.incidentId = incidentId;
        return this;
    }

    /**
     * Filter by the incident id.
     * @return incidentId
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_INCIDENT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getIncidentId() {
        return incidentId;
    }

    @JsonProperty(JSON_PROPERTY_INCIDENT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIncidentId(String incidentId) {
        this.incidentId = incidentId;
    }

    public ProcessInstanceQueryDto incidentType(String incidentType) {
        this.incidentType = incidentType;
        return this;
    }

    /**
     * Filter by the incident type. See the User Guide for a list of incident types.
     * @return incidentType
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_INCIDENT_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getIncidentType() {
        return incidentType;
    }

    @JsonProperty(JSON_PROPERTY_INCIDENT_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIncidentType(String incidentType) {
        this.incidentType = incidentType;
    }

    public ProcessInstanceQueryDto incidentMessage(String incidentMessage) {
        this.incidentMessage = incidentMessage;
        return this;
    }

    /**
     * Filter by the incident message. Exact match.
     * @return incidentMessage
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_INCIDENT_MESSAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getIncidentMessage() {
        return incidentMessage;
    }

    @JsonProperty(JSON_PROPERTY_INCIDENT_MESSAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIncidentMessage(String incidentMessage) {
        this.incidentMessage = incidentMessage;
    }

    public ProcessInstanceQueryDto incidentMessageLike(String incidentMessageLike) {
        this.incidentMessageLike = incidentMessageLike;
        return this;
    }

    /**
     * Filter by the incident message that the parameter is a substring of.
     * @return incidentMessageLike
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_INCIDENT_MESSAGE_LIKE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getIncidentMessageLike() {
        return incidentMessageLike;
    }

    @JsonProperty(JSON_PROPERTY_INCIDENT_MESSAGE_LIKE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIncidentMessageLike(String incidentMessageLike) {
        this.incidentMessageLike = incidentMessageLike;
    }

    public ProcessInstanceQueryDto tenantIdIn(List<String> tenantIdIn) {
        this.tenantIdIn = tenantIdIn;
        return this;
    }

    public ProcessInstanceQueryDto addTenantIdInItem(String tenantIdInItem) {
        if (this.tenantIdIn == null) {
            this.tenantIdIn = new ArrayList<>();
        }
        this.tenantIdIn.add(tenantIdInItem);
        return this;
    }

    /**
     * Filter by a list of tenant ids. A process instance must have one of the given tenant ids. Must be a JSON array of Strings.
     * @return tenantIdIn
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_TENANT_ID_IN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<String> getTenantIdIn() {
        return tenantIdIn;
    }

    @JsonProperty(JSON_PROPERTY_TENANT_ID_IN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTenantIdIn(List<String> tenantIdIn) {
        this.tenantIdIn = tenantIdIn;
    }

    public ProcessInstanceQueryDto withoutTenantId(Boolean withoutTenantId) {
        this.withoutTenantId = withoutTenantId;
        return this;
    }

    /**
     * Only include process instances which belong to no tenant. Value may only be true, as false is the default behavior.
     * @return withoutTenantId
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_WITHOUT_TENANT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getWithoutTenantId() {
        return withoutTenantId;
    }

    @JsonProperty(JSON_PROPERTY_WITHOUT_TENANT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setWithoutTenantId(Boolean withoutTenantId) {
        this.withoutTenantId = withoutTenantId;
    }

    public ProcessInstanceQueryDto processDefinitionWithoutTenantId(Boolean processDefinitionWithoutTenantId) {
        this.processDefinitionWithoutTenantId = processDefinitionWithoutTenantId;
        return this;
    }

    /**
     * Only include process instances which process definition has no tenant id.
     * @return processDefinitionWithoutTenantId
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_PROCESS_DEFINITION_WITHOUT_TENANT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getProcessDefinitionWithoutTenantId() {
        return processDefinitionWithoutTenantId;
    }

    @JsonProperty(JSON_PROPERTY_PROCESS_DEFINITION_WITHOUT_TENANT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProcessDefinitionWithoutTenantId(Boolean processDefinitionWithoutTenantId) {
        this.processDefinitionWithoutTenantId = processDefinitionWithoutTenantId;
    }

    public ProcessInstanceQueryDto activityIdIn(List<String> activityIdIn) {
        this.activityIdIn = activityIdIn;
        return this;
    }

    public ProcessInstanceQueryDto addActivityIdInItem(String activityIdInItem) {
        if (this.activityIdIn == null) {
            this.activityIdIn = new ArrayList<>();
        }
        this.activityIdIn.add(activityIdInItem);
        return this;
    }

    /**
     * Filter by a list of activity ids. A process instance must currently wait in a leaf activity with one of the given activity ids.
     * @return activityIdIn
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_ACTIVITY_ID_IN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<String> getActivityIdIn() {
        return activityIdIn;
    }

    @JsonProperty(JSON_PROPERTY_ACTIVITY_ID_IN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setActivityIdIn(List<String> activityIdIn) {
        this.activityIdIn = activityIdIn;
    }

    public ProcessInstanceQueryDto rootProcessInstances(Boolean rootProcessInstances) {
        this.rootProcessInstances = rootProcessInstances;
        return this;
    }

    /**
     * Restrict the query to all process instances that are top level process instances.
     * @return rootProcessInstances
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_ROOT_PROCESS_INSTANCES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getRootProcessInstances() {
        return rootProcessInstances;
    }

    @JsonProperty(JSON_PROPERTY_ROOT_PROCESS_INSTANCES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRootProcessInstances(Boolean rootProcessInstances) {
        this.rootProcessInstances = rootProcessInstances;
    }

    public ProcessInstanceQueryDto leafProcessInstances(Boolean leafProcessInstances) {
        this.leafProcessInstances = leafProcessInstances;
        return this;
    }

    /**
     * Restrict the query to all process instances that are leaf instances. (i.e. don&#39;t have any sub instances)
     * @return leafProcessInstances
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_LEAF_PROCESS_INSTANCES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getLeafProcessInstances() {
        return leafProcessInstances;
    }

    @JsonProperty(JSON_PROPERTY_LEAF_PROCESS_INSTANCES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLeafProcessInstances(Boolean leafProcessInstances) {
        this.leafProcessInstances = leafProcessInstances;
    }

    public ProcessInstanceQueryDto variables(List<VariableQueryParameterDto> variables) {
        this.variables = variables;
        return this;
    }

    public ProcessInstanceQueryDto addVariablesItem(VariableQueryParameterDto variablesItem) {
        if (this.variables == null) {
            this.variables = new ArrayList<>();
        }
        this.variables.add(variablesItem);
        return this;
    }

    /**
     * A JSON array to only include process instances that have variables with certain values. The array consists of objects with the three properties &#x60;name&#x60;, &#x60;operator&#x60; and &#x60;value&#x60;. &#x60;name&#x60; (String) is the variable name, &#x60;operator&#x60; (String) is the comparison operator to be used and &#x60;value&#x60; the variable value. The &#x60;value&#x60; may be String, Number or Boolean.  Valid operator values are: &#x60;eq&#x60; - equal to; &#x60;neq&#x60; - not equal to; &#x60;gt&#x60; - greater than; &#x60;gteq&#x60; - greater than or equal to; &#x60;lt&#x60; - lower than; &#x60;lteq&#x60; - lower than or equal to; &#x60;like&#x60;.
     * @return variables
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_VARIABLES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<VariableQueryParameterDto> getVariables() {
        return variables;
    }

    @JsonProperty(JSON_PROPERTY_VARIABLES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVariables(List<VariableQueryParameterDto> variables) {
        this.variables = variables;
    }

    public ProcessInstanceQueryDto variableNamesIgnoreCase(Boolean variableNamesIgnoreCase) {
        this.variableNamesIgnoreCase = variableNamesIgnoreCase;
        return this;
    }

    /**
     * Match all variable names in this query case-insensitively. If set to true variableName and variablename are treated as equal.
     * @return variableNamesIgnoreCase
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_VARIABLE_NAMES_IGNORE_CASE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getVariableNamesIgnoreCase() {
        return variableNamesIgnoreCase;
    }

    @JsonProperty(JSON_PROPERTY_VARIABLE_NAMES_IGNORE_CASE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVariableNamesIgnoreCase(Boolean variableNamesIgnoreCase) {
        this.variableNamesIgnoreCase = variableNamesIgnoreCase;
    }

    public ProcessInstanceQueryDto variableValuesIgnoreCase(Boolean variableValuesIgnoreCase) {
        this.variableValuesIgnoreCase = variableValuesIgnoreCase;
        return this;
    }

    /**
     * Match all variable values in this query case-insensitively. If set to true variableValue and variablevalue are treated as equal.
     * @return variableValuesIgnoreCase
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_VARIABLE_VALUES_IGNORE_CASE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getVariableValuesIgnoreCase() {
        return variableValuesIgnoreCase;
    }

    @JsonProperty(JSON_PROPERTY_VARIABLE_VALUES_IGNORE_CASE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVariableValuesIgnoreCase(Boolean variableValuesIgnoreCase) {
        this.variableValuesIgnoreCase = variableValuesIgnoreCase;
    }

    public ProcessInstanceQueryDto orQueries(List<ProcessInstanceQueryDto> orQueries) {
        this.orQueries = orQueries;
        return this;
    }

    public ProcessInstanceQueryDto addOrQueriesItem(ProcessInstanceQueryDto orQueriesItem) {
        if (this.orQueries == null) {
            this.orQueries = new ArrayList<>();
        }
        this.orQueries.add(orQueriesItem);
        return this;
    }

    /**
     * A JSON array of nested process instance queries with OR semantics. A process instance matches a nested query if it fulfills at least one of the query&#39;s predicates. With multiple nested queries, a process instance must fulfill at least one predicate of each query (Conjunctive Normal Form). All process instance query properties can be used except for: &#x60;sorting&#x60; See the [User guide](https://docs.camunda.org/manual/7.18/user-guide/process-engine/process-engine-api/#or-queries) for more information about OR queries.
     * @return orQueries
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_OR_QUERIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<ProcessInstanceQueryDto> getOrQueries() {
        return orQueries;
    }

    @JsonProperty(JSON_PROPERTY_OR_QUERIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setOrQueries(List<ProcessInstanceQueryDto> orQueries) {
        this.orQueries = orQueries;
    }

    public ProcessInstanceQueryDto sorting(List<ProcessInstanceQueryDtoSortingInner> sorting) {
        this.sorting = sorting;
        return this;
    }

    public ProcessInstanceQueryDto addSortingItem(ProcessInstanceQueryDtoSortingInner sortingItem) {
        if (this.sorting == null) {
            this.sorting = new ArrayList<>();
        }
        this.sorting.add(sortingItem);
        return this;
    }

    /**
     * Apply sorting of the result
     * @return sorting
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_SORTING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<ProcessInstanceQueryDtoSortingInner> getSorting() {
        return sorting;
    }

    @JsonProperty(JSON_PROPERTY_SORTING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSorting(List<ProcessInstanceQueryDtoSortingInner> sorting) {
        this.sorting = sorting;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProcessInstanceQueryDto processInstanceQueryDto = (ProcessInstanceQueryDto) o;
        return Objects.equals(this.deploymentId, processInstanceQueryDto.deploymentId) &&
            Objects.equals(this.processDefinitionId, processInstanceQueryDto.processDefinitionId) &&
            Objects.equals(this.processDefinitionKey, processInstanceQueryDto.processDefinitionKey) &&
            Objects.equals(this.processDefinitionKeyIn, processInstanceQueryDto.processDefinitionKeyIn) &&
            Objects.equals(this.processDefinitionKeyNotIn, processInstanceQueryDto.processDefinitionKeyNotIn) &&
            Objects.equals(this.businessKey, processInstanceQueryDto.businessKey) &&
            Objects.equals(this.businessKeyLike, processInstanceQueryDto.businessKeyLike) &&
            Objects.equals(this.caseInstanceId, processInstanceQueryDto.caseInstanceId) &&
            Objects.equals(this.superProcessInstance, processInstanceQueryDto.superProcessInstance) &&
            Objects.equals(this.subProcessInstance, processInstanceQueryDto.subProcessInstance) &&
            Objects.equals(this.superCaseInstance, processInstanceQueryDto.superCaseInstance) &&
            Objects.equals(this.subCaseInstance, processInstanceQueryDto.subCaseInstance) &&
            Objects.equals(this.active, processInstanceQueryDto.active) &&
            Objects.equals(this.suspended, processInstanceQueryDto.suspended) &&
            Objects.equals(this.processInstanceIds, processInstanceQueryDto.processInstanceIds) &&
            Objects.equals(this.withIncident, processInstanceQueryDto.withIncident) &&
            Objects.equals(this.incidentId, processInstanceQueryDto.incidentId) &&
            Objects.equals(this.incidentType, processInstanceQueryDto.incidentType) &&
            Objects.equals(this.incidentMessage, processInstanceQueryDto.incidentMessage) &&
            Objects.equals(this.incidentMessageLike, processInstanceQueryDto.incidentMessageLike) &&
            Objects.equals(this.tenantIdIn, processInstanceQueryDto.tenantIdIn) &&
            Objects.equals(this.withoutTenantId, processInstanceQueryDto.withoutTenantId) &&
            Objects.equals(this.processDefinitionWithoutTenantId, processInstanceQueryDto.processDefinitionWithoutTenantId) &&
            Objects.equals(this.activityIdIn, processInstanceQueryDto.activityIdIn) &&
            Objects.equals(this.rootProcessInstances, processInstanceQueryDto.rootProcessInstances) &&
            Objects.equals(this.leafProcessInstances, processInstanceQueryDto.leafProcessInstances) &&
            Objects.equals(this.variables, processInstanceQueryDto.variables) &&
            Objects.equals(this.variableNamesIgnoreCase, processInstanceQueryDto.variableNamesIgnoreCase) &&
            Objects.equals(this.variableValuesIgnoreCase, processInstanceQueryDto.variableValuesIgnoreCase) &&
            Objects.equals(this.orQueries, processInstanceQueryDto.orQueries) &&
            Objects.equals(this.sorting, processInstanceQueryDto.sorting);
    }

    @Override
    public int hashCode() {
        return Objects.hash(deploymentId, processDefinitionId, processDefinitionKey, processDefinitionKeyIn, processDefinitionKeyNotIn, businessKey, businessKeyLike, caseInstanceId, superProcessInstance, subProcessInstance, superCaseInstance, subCaseInstance, active, suspended, processInstanceIds, withIncident, incidentId, incidentType, incidentMessage, incidentMessageLike, tenantIdIn, withoutTenantId, processDefinitionWithoutTenantId, activityIdIn, rootProcessInstances, leafProcessInstances, variables, variableNamesIgnoreCase, variableValuesIgnoreCase, orQueries, sorting);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ProcessInstanceQueryDto {\n");
        sb.append("    deploymentId: ").append(toIndentedString(deploymentId)).append("\n");
        sb.append("    processDefinitionId: ").append(toIndentedString(processDefinitionId)).append("\n");
        sb.append("    processDefinitionKey: ").append(toIndentedString(processDefinitionKey)).append("\n");
        sb.append("    processDefinitionKeyIn: ").append(toIndentedString(processDefinitionKeyIn)).append("\n");
        sb.append("    processDefinitionKeyNotIn: ").append(toIndentedString(processDefinitionKeyNotIn)).append("\n");
        sb.append("    businessKey: ").append(toIndentedString(businessKey)).append("\n");
        sb.append("    businessKeyLike: ").append(toIndentedString(businessKeyLike)).append("\n");
        sb.append("    caseInstanceId: ").append(toIndentedString(caseInstanceId)).append("\n");
        sb.append("    superProcessInstance: ").append(toIndentedString(superProcessInstance)).append("\n");
        sb.append("    subProcessInstance: ").append(toIndentedString(subProcessInstance)).append("\n");
        sb.append("    superCaseInstance: ").append(toIndentedString(superCaseInstance)).append("\n");
        sb.append("    subCaseInstance: ").append(toIndentedString(subCaseInstance)).append("\n");
        sb.append("    active: ").append(toIndentedString(active)).append("\n");
        sb.append("    suspended: ").append(toIndentedString(suspended)).append("\n");
        sb.append("    processInstanceIds: ").append(toIndentedString(processInstanceIds)).append("\n");
        sb.append("    withIncident: ").append(toIndentedString(withIncident)).append("\n");
        sb.append("    incidentId: ").append(toIndentedString(incidentId)).append("\n");
        sb.append("    incidentType: ").append(toIndentedString(incidentType)).append("\n");
        sb.append("    incidentMessage: ").append(toIndentedString(incidentMessage)).append("\n");
        sb.append("    incidentMessageLike: ").append(toIndentedString(incidentMessageLike)).append("\n");
        sb.append("    tenantIdIn: ").append(toIndentedString(tenantIdIn)).append("\n");
        sb.append("    withoutTenantId: ").append(toIndentedString(withoutTenantId)).append("\n");
        sb.append("    processDefinitionWithoutTenantId: ").append(toIndentedString(processDefinitionWithoutTenantId)).append("\n");
        sb.append("    activityIdIn: ").append(toIndentedString(activityIdIn)).append("\n");
        sb.append("    rootProcessInstances: ").append(toIndentedString(rootProcessInstances)).append("\n");
        sb.append("    leafProcessInstances: ").append(toIndentedString(leafProcessInstances)).append("\n");
        sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
        sb.append("    variableNamesIgnoreCase: ").append(toIndentedString(variableNamesIgnoreCase)).append("\n");
        sb.append("    variableValuesIgnoreCase: ").append(toIndentedString(variableValuesIgnoreCase)).append("\n");
        sb.append("    orQueries: ").append(toIndentedString(orQueries)).append("\n");
        sb.append("    sorting: ").append(toIndentedString(sorting)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

