/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.camunda.rest.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.Nullable;

import javax.annotation.Generated;
import java.util.*;

/**
 * TelemetryInternalsDto
 */
@JsonPropertyOrder({
  TelemetryInternalsDto.JSON_PROPERTY_DATABASE,
  TelemetryInternalsDto.JSON_PROPERTY_APPLICATION_SERVER,
  TelemetryInternalsDto.JSON_PROPERTY_LICENSE_KEY,
  TelemetryInternalsDto.JSON_PROPERTY_CAMUNDA_INTEGRATION,
  TelemetryInternalsDto.JSON_PROPERTY_COMMANDS,
  TelemetryInternalsDto.JSON_PROPERTY_METRICS,
  TelemetryInternalsDto.JSON_PROPERTY_WEBAPPS,
  TelemetryInternalsDto.JSON_PROPERTY_JDK
})
@JsonTypeName("TelemetryInternalsDto")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen")
@Introspected
public class TelemetryInternalsDto {
    public static final String JSON_PROPERTY_DATABASE = "database";
    private Map<String, AbstractVendorVersionInformationDto> database = null;

    public static final String JSON_PROPERTY_APPLICATION_SERVER = "application-server";
    private Map<String, AbstractVendorVersionInformationDto> applicationServer = null;

    public static final String JSON_PROPERTY_LICENSE_KEY = "license-key";
    private Map<String, TelemetryLicenseKeyDto> licenseKey = null;

    public static final String JSON_PROPERTY_CAMUNDA_INTEGRATION = "camunda-integration";
    private List<String> camundaIntegration = null;

    public static final String JSON_PROPERTY_COMMANDS = "commands";
    private Map<String, TelemetryCountDto> commands = null;

    public static final String JSON_PROPERTY_METRICS = "metrics";
    private Map<String, TelemetryCountDto> metrics = null;

    public static final String JSON_PROPERTY_WEBAPPS = "webapps";
    private List<String> webapps = null;

    public static final String JSON_PROPERTY_JDK = "jdk";
    private Map<String, AbstractVendorVersionInformationDto> jdk = null;

    public TelemetryInternalsDto() {
    }

    public TelemetryInternalsDto database(Map<String, AbstractVendorVersionInformationDto> database) {
        this.database = database;
        return this;
    }

    public TelemetryInternalsDto putDatabaseItem(String key, AbstractVendorVersionInformationDto databaseItem) {
        if (this.database == null) {
            this.database = new HashMap<>();
        }
        this.database.put(key, databaseItem);
        return this;
  }

    /**
     * Vendor and version of the connected database.
     * @return database
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_DATABASE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Map<String, AbstractVendorVersionInformationDto> getDatabase() {
        return database;
    }

    @JsonProperty(JSON_PROPERTY_DATABASE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDatabase(Map<String, AbstractVendorVersionInformationDto> database) {
        this.database = database;
    }

    public TelemetryInternalsDto applicationServer(Map<String, AbstractVendorVersionInformationDto> applicationServer) {
        this.applicationServer = applicationServer;
        return this;
    }

    public TelemetryInternalsDto putApplicationServerItem(String key, AbstractVendorVersionInformationDto applicationServerItem) {
        if (this.applicationServer == null) {
            this.applicationServer = new HashMap<>();
        }
        this.applicationServer.put(key, applicationServerItem);
        return this;
  }

    /**
     * Vendor and version of the application server.
     * @return applicationServer
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_APPLICATION_SERVER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Map<String, AbstractVendorVersionInformationDto> getApplicationServer() {
        return applicationServer;
    }

    @JsonProperty(JSON_PROPERTY_APPLICATION_SERVER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setApplicationServer(Map<String, AbstractVendorVersionInformationDto> applicationServer) {
        this.applicationServer = applicationServer;
    }

    public TelemetryInternalsDto licenseKey(Map<String, TelemetryLicenseKeyDto> licenseKey) {
        this.licenseKey = licenseKey;
        return this;
    }

    public TelemetryInternalsDto putLicenseKeyItem(String key, TelemetryLicenseKeyDto licenseKeyItem) {
        if (this.licenseKey == null) {
            this.licenseKey = new HashMap<>();
        }
        this.licenseKey.put(key, licenseKeyItem);
        return this;
  }

    /**
     * Information about the Camunda license key.
     * @return licenseKey
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_LICENSE_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Map<String, TelemetryLicenseKeyDto> getLicenseKey() {
        return licenseKey;
    }

    @JsonProperty(JSON_PROPERTY_LICENSE_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLicenseKey(Map<String, TelemetryLicenseKeyDto> licenseKey) {
        this.licenseKey = licenseKey;
    }

    public TelemetryInternalsDto camundaIntegration(List<String> camundaIntegration) {
        this.camundaIntegration = camundaIntegration;
        return this;
    }

    public TelemetryInternalsDto addCamundaIntegrationItem(String camundaIntegrationItem) {
        if (this.camundaIntegration == null) {
            this.camundaIntegration = new ArrayList<>();
        }
        this.camundaIntegration.add(camundaIntegrationItem);
        return this;
    }

    /**
     * List of Camunda integrations used (e.g., Camunda Spring Boot Starter, Camunda Run, WildFly/JBoss subsystem, Camunda EJB).
     * @return camundaIntegration
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_CAMUNDA_INTEGRATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<String> getCamundaIntegration() {
        return camundaIntegration;
    }

    @JsonProperty(JSON_PROPERTY_CAMUNDA_INTEGRATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCamundaIntegration(List<String> camundaIntegration) {
        this.camundaIntegration = camundaIntegration;
    }

    public TelemetryInternalsDto commands(Map<String, TelemetryCountDto> commands) {
        this.commands = commands;
        return this;
    }

    public TelemetryInternalsDto putCommandsItem(String key, TelemetryCountDto commandsItem) {
        if (this.commands == null) {
            this.commands = new HashMap<>();
        }
        this.commands.put(key, commandsItem);
        return this;
  }

    /**
     * The count of executed commands after the last retrieved data.
     * @return commands
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_COMMANDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Map<String, TelemetryCountDto> getCommands() {
        return commands;
    }

    @JsonProperty(JSON_PROPERTY_COMMANDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCommands(Map<String, TelemetryCountDto> commands) {
        this.commands = commands;
    }

    public TelemetryInternalsDto metrics(Map<String, TelemetryCountDto> metrics) {
        this.metrics = metrics;
        return this;
    }

    public TelemetryInternalsDto putMetricsItem(String key, TelemetryCountDto metricsItem) {
        if (this.metrics == null) {
            this.metrics = new HashMap<>();
        }
        this.metrics.put(key, metricsItem);
        return this;
  }

    /**
     * The collected metrics are the number of root process instance executions started, the number of activity instances started or also known as flow node instances, and the number of executed decision instances and elements.
     * @return metrics
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_METRICS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Map<String, TelemetryCountDto> getMetrics() {
        return metrics;
    }

    @JsonProperty(JSON_PROPERTY_METRICS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMetrics(Map<String, TelemetryCountDto> metrics) {
        this.metrics = metrics;
    }

    public TelemetryInternalsDto webapps(List<String> webapps) {
        this.webapps = webapps;
        return this;
    }

    public TelemetryInternalsDto addWebappsItem(String webappsItem) {
        if (this.webapps == null) {
            this.webapps = new ArrayList<>();
        }
        this.webapps.add(webappsItem);
        return this;
    }

    /**
     * The webapps enabled in this installation of Camunda.
     * @return webapps
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_WEBAPPS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<String> getWebapps() {
        return webapps;
    }

    @JsonProperty(JSON_PROPERTY_WEBAPPS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setWebapps(List<String> webapps) {
        this.webapps = webapps;
    }

    public TelemetryInternalsDto jdk(Map<String, AbstractVendorVersionInformationDto> jdk) {
        this.jdk = jdk;
        return this;
    }

    public TelemetryInternalsDto putJdkItem(String key, AbstractVendorVersionInformationDto jdkItem) {
        if (this.jdk == null) {
            this.jdk = new HashMap<>();
        }
        this.jdk.put(key, jdkItem);
        return this;
  }

    /**
     * Vendor and version of the installed JDK.
     * @return jdk
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_JDK)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Map<String, AbstractVendorVersionInformationDto> getJdk() {
        return jdk;
    }

    @JsonProperty(JSON_PROPERTY_JDK)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setJdk(Map<String, AbstractVendorVersionInformationDto> jdk) {
        this.jdk = jdk;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TelemetryInternalsDto telemetryInternalsDto = (TelemetryInternalsDto) o;
        return Objects.equals(this.database, telemetryInternalsDto.database) &&
            Objects.equals(this.applicationServer, telemetryInternalsDto.applicationServer) &&
            Objects.equals(this.licenseKey, telemetryInternalsDto.licenseKey) &&
            Objects.equals(this.camundaIntegration, telemetryInternalsDto.camundaIntegration) &&
            Objects.equals(this.commands, telemetryInternalsDto.commands) &&
            Objects.equals(this.metrics, telemetryInternalsDto.metrics) &&
            Objects.equals(this.webapps, telemetryInternalsDto.webapps) &&
            Objects.equals(this.jdk, telemetryInternalsDto.jdk);
    }

    @Override
    public int hashCode() {
        return Objects.hash(database, applicationServer, licenseKey, camundaIntegration, commands, metrics, webapps, jdk);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TelemetryInternalsDto {\n");
        sb.append("    database: ").append(toIndentedString(database)).append("\n");
        sb.append("    applicationServer: ").append(toIndentedString(applicationServer)).append("\n");
        sb.append("    licenseKey: ").append(toIndentedString(licenseKey)).append("\n");
        sb.append("    camundaIntegration: ").append(toIndentedString(camundaIntegration)).append("\n");
        sb.append("    commands: ").append(toIndentedString(commands)).append("\n");
        sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
        sb.append("    webapps: ").append(toIndentedString(webapps)).append("\n");
        sb.append("    jdk: ").append(toIndentedString(jdk)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

