/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.camunda.rest.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.Nullable;

import javax.annotation.Generated;
import java.util.Objects;

/**
 * TriggerVariableValueDtoAllOf
 */
@JsonPropertyOrder({
  TriggerVariableValueDtoAllOf.JSON_PROPERTY_LOCAL
})
@JsonTypeName("TriggerVariableValueDto_allOf")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen")
@Introspected
public class TriggerVariableValueDtoAllOf {
    public static final String JSON_PROPERTY_LOCAL = "local";
    private Boolean local;

    public TriggerVariableValueDtoAllOf() {
    }

    public TriggerVariableValueDtoAllOf local(Boolean local) {
        this.local = local;
        return this;
    }

    /**
     * Indicates whether the variable should be a local variable or not. If set to true, the variable becomes a local variable of the execution entering the target activity.
     * @return local
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_LOCAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getLocal() {
        return local;
    }

    @JsonProperty(JSON_PROPERTY_LOCAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLocal(Boolean local) {
        this.local = local;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TriggerVariableValueDtoAllOf triggerVariableValueDtoAllOf = (TriggerVariableValueDtoAllOf) o;
        return Objects.equals(this.local, triggerVariableValueDtoAllOf.local);
    }

    @Override
    public int hashCode() {
        return Objects.hash(local);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TriggerVariableValueDtoAllOf {\n");
        sb.append("    local: ").append(toIndentedString(local)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

