/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.camunda.rest.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.Nullable;

import javax.annotation.Generated;
import java.util.Objects;

/**
 * UserCredentialsDto
 */
@JsonPropertyOrder({
  UserCredentialsDto.JSON_PROPERTY_PASSWORD,
  UserCredentialsDto.JSON_PROPERTY_AUTHENTICATED_USER_PASSWORD
})
@JsonTypeName("UserCredentialsDto")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen")
@Introspected
public class UserCredentialsDto {
    public static final String JSON_PROPERTY_PASSWORD = "password";
    private String password;

    public static final String JSON_PROPERTY_AUTHENTICATED_USER_PASSWORD = "authenticatedUserPassword";
    private String authenticatedUserPassword;

    public UserCredentialsDto() {
    }

    public UserCredentialsDto password(String password) {
        this.password = password;
        return this;
    }

    /**
     * The users new password.
     * @return password
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_PASSWORD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getPassword() {
        return password;
    }

    @JsonProperty(JSON_PROPERTY_PASSWORD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPassword(String password) {
        this.password = password;
    }

    public UserCredentialsDto authenticatedUserPassword(String authenticatedUserPassword) {
        this.authenticatedUserPassword = authenticatedUserPassword;
        return this;
    }

    /**
     * The password of the authenticated user who changes the password of the user (i.e., the user with passed id as path parameter).
     * @return authenticatedUserPassword
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_AUTHENTICATED_USER_PASSWORD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getAuthenticatedUserPassword() {
        return authenticatedUserPassword;
    }

    @JsonProperty(JSON_PROPERTY_AUTHENTICATED_USER_PASSWORD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAuthenticatedUserPassword(String authenticatedUserPassword) {
        this.authenticatedUserPassword = authenticatedUserPassword;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserCredentialsDto userCredentialsDto = (UserCredentialsDto) o;
        return Objects.equals(this.password, userCredentialsDto.password) &&
            Objects.equals(this.authenticatedUserPassword, userCredentialsDto.authenticatedUserPassword);
    }

    @Override
    public int hashCode() {
        return Objects.hash(password, authenticatedUserPassword);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserCredentialsDto {\n");
        sb.append("    password: ").append(toIndentedString(password)).append("\n");
        sb.append("    authenticatedUserPassword: ").append(toIndentedString(authenticatedUserPassword)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

