/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.camunda.rest.api;

import io.micronaut.http.annotation.Consumes;
import io.micronaut.http.annotation.Get;
import io.micronaut.http.client.annotation.Client;
import org.camunda.rest.model.VersionDto;
import reactor.core.publisher.Mono;

import javax.annotation.Generated;

@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen")
@Client("${openapi-micronaut-client-base-path}")
public interface VersionApi {
    /**
     * Get Rest API version
     * Retrieves the version of the Rest API.
     *
     * @return VersionDto
     */
    @Get(uri="/version")
    @Consumes({"application/json"})
    Mono<VersionDto> getRestAPIVersion();

}
